### ISSUE TITLE
line numbers

### ISSUE THREAD

**Issue by rcrooks** [karl/vscode-karl-okeeffes-theme#1]
Hi @karl I like your theme a great deal - there's only one drawback: the line numbers are too faint to read, and I work in a lot of long files where that's really a drawback. Would you willing to lighten them up just a little to increase the contrast with the background?

Thanks for considering!

**Comment by karl** [comment]
Hi!

Thanks for the message. I’m amazed to find out someone other than me is
using my theme!

I’m definitely happy to look at making the line numbers easier to read.

Do you feel comfortable raising a PR to make the change? If so I’m happy to
merge and publish a new version. If not, I’ll take a look when I have a
spare moment (which will probably be some time next week).

**Comment by rcrooks** [comment]
I do indeed -- I'll make the change and raise the PR. Thanks!

**Comment by karl** [comment]
I've incorporated this change in the latest release by including a new Variant version of the theme with lighter line numbers.

If you update to 5.0.4, you can choose the "Karl O'Keeffe's Theme (Variant)" theme in order to get lighter line numbers.

**Comment by rcrooks** [comment]
Got it - thanks!
